services:
  postgres:
    container_name: troca-livros-postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    env_file:
      - path: .env
        required: true
        
  postgres_test:
    container_name: troca-livros-postgres-test
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB:-test_db}
    volumes:
      - ./postgres/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    restart: always
    env_file:
      - path: .env
        required: true

volumes:
  postgres:
    driver: local