# Arquivo de configuração do cargo-tarpaulin
[all]

# Exclui arquivos específicos da cobertura
exclude-files = [
    "src/main.rs",
    "src/docs/*"
]

skip-clean=true

# Opções de saída 
out = ["Html"]
