# Arquivo de configuração do cargo-tarpaulin
[all]

test-threads = 1

# Exclui arquivos específicos da cobertura
exclude-files = [
    "src/main.rs",
    "src/docs/*"
]

# Opções de saída 
out = ["Html"]